server:
  port: 8181

spring:
  application:
    name: app-server-domain-product
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public

dubbo:
  scan:
    base-packages: com.soyokra.learn.product.rpc.provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address:  spring-cloud://localhost
  cloud:
    subscribed-services: app-server-domain-order